---
allspark_docker_version: "18.06"
allspark_root_directory: "/opt/allspark/"
artifactorydb_password: "MyLovelyArtifactory31"

allspark_nginx:
 enabled: true
 ssl: false

allspark_artifactory:
 enabled: true