---
allspark_docker_version: "18.06"
allspark_root_directory: "/opt/allspark/"
artifactorydb_password: "MyLovelyArtifactory31"

allspark_nginx:
 enabled: true
 ssl: false

allspark_artifactory:
 enabled: true

allspark_artifactory_postgres:
 enabled: false

allspark_xray:
 enabled: true
 xray_data: ""
 ports: ""
 mount_root: ""
 postgres_user: ""
 postgres_password: ""
 rabbitmq_erlang_cookie: ""
 
