---
allspark_docker_version: "18.06"
allspark_root_directory: "/opt/allspark/"
artifactorydb_password: "MyLovelyArtifactory31"

allspark_nginx:
 enabled: true
 ssl: false

allspark_artifactory:
 enabled: true

allspark_artifactory_postgres:
 enabled: false

allspark_xray:
 enabled: true
 xray_data: ""
 ports: ""
 mount_root: ""
 postgres_user: ""
 postgres_password: ""
 rabbitmq_erlang_cookie: ""

# Images
centos_image: centos
artipostgresql_image: docker.bintray.io/postgres
artifactory_image: docker.bintray.io/jfrog/artifactory-pro
nginx_image: docker.bintray.io/jfrog/nginx-artifactory-pro
xrayserver_image: docker.bintray.io/jfrog/xray-server
xrayindexer_image: docker.bintray.io/jfrog/xray-indexer
xraypersist_image: docker.bintray.io/jfrog/xray-persist
xrayanalysis_image: docker.bintray.io/jfrog/xray-analysis
xrayrabbitmq_image: docker.bintray.io/jfrog/xray-rabbitmq
xraymongodb_image: docker.bintray.io/jfrog/xray-mongo
xraypostgresql_image: docker.bintray.io/postgres
# Tags
# Alpine tag is required, because it bundle rsyslogd
# which allow us to read logs from HAProxy
centos_tag: 7
artipostgresql_tag: 9.6.11
artifactory_tag: 6.10.4
nginx_tag: 6.10.4
xraymongodb_tag: 3.2.6
xraypostgresql_tag: 9.6.11
xrayrabbitmq_tag: 3.7.0-management
xray_tag: 2.8.0

# Downloads
downloads:
  centos:
    enabled: true
    image: "{{ centos_image }}"
    tag: "{{ centos_tag }}"
  artipostgresql:
    enabled: "{{ allspark_artifactory.enabled }}"
    image: "{{ artipostgresql_image }}"
    tag: "{{ artipostgresql_tag }}"
  artifactory:
    enabled: "{{ allspark_artifactory.enabled }}"
    image: "{{ artifactory_image }}"
    tag: "{{ artifactory_tag }}"
  nginx:
    enabled: "{{ allspark_nginx.enabled }}"
    image: "{{ nginx_image }}"
    tag: "{{ nginx_tag }}"
  xrayserver:
    enabled: "{{ allspark_xray.enabled }}"
    image: "{{ xrayserver_image }}"
    tag: "{{ xray_tag }}"
  xrayindexer:
    enabled: "{{ allspark_xray.enabled }}"
    image: "{{ xrayindexer_image }}"
    tag: "{{ xray_tag }}"
  xraypersist:
    enabled: "{{ allspark_xray.enabled }}"
    image: "{{ xraypersist_image }}"
    tag: "{{ xray_tag }}"
  xrayanalysis:
    enabled: "{{ allspark_xray.enabled }}"
    image: "{{ xrayanalysis_image }}"
    tag: "{{ xray_tag }}"
  xrayrabbitmq:
    enabled: "{{ allspark_xray.enabled }}"
    image: "{{ xrayrabbitmq_image }}"
    tag: "{{ xrayrabbitmq_tag }}"
  xraypostgresql:
    enabled: "{{ allspark_xray.enabled }}"
    image: "{{ xraypostgresql_image }}"
    tag: "{{ xraypostgresql_tag }}"
  xraymongodb:
    enabled: "{{ allspark_xray.enabled }}"
    image: "{{ xraymongodb_image }}"
    tag: "{{ xraymongodb_tag }}"
# Misc

## Set this to true to force the download of every images, even if they are
## disabled in the configuration
force_download: false
 
